### ISSUE TITLE
move search button a little more into the appbar

### ISSUE THREAD

**Issue by Sami-ul** [Sami-ul/tabmanager#17]

**Comment by kartikey4474** [comment]
I want to work on this issue. please assign it to me.

**Comment by Sami-ul** [comment]
@kartikey4474 hey sure but can you work on a couple others also?

**Comment by kartikey4474** [comment]
can you please provide more clarity regarding this issue. where you want your search button to be ?

**Comment by Sami-ul** [comment]
It is too far to the right move it left in the app bar

**Comment by kartikey4474** [comment]
I have updated the code. and added padding instead of using container. this looks fine now. also i have stared the repo. looking for future contributions.
