### ISSUE TITLE
Make snackbar text look better

### ISSUE THREAD

**Issue by Sami-ul** [Sami-ul/tabmanager#3]
Make it white and increase size a little, maybe also change the positioning

**Comment by Krishpandya682** [comment]
Hi, I would like to work on this issue

**Comment by Sami-ul** [comment]
@Krishpandya682 Go for it! Star the project if you haven't. Let me know if you need any advice of help.

**Comment by Sami-ul** [comment]
Also be sure to set up the postgres db, I am happy to help if you need it. Heres the guide I used: https://blog.logrocket.com/crud-rest-api-node-js-express-postgresql/

**Comment by Sami-ul** [comment]
Done
